name: wtf_sliding_sheet
description: A widget that can be dragged and scrolled in a single gesture and snapped to a list of extents.
version: 1.1.0
homepage: https://pub.dev/packages/wtf_sliding_sheet
repository: https://github.com/What-the-Flutter/wtf_sliding_sheet

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
