name: WTF Sliding Sheet CI/CD

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: Analyze and pana check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Analyzing
        run: flutter analyze

      - name: Pana check
        run: |
          chmod +x pana_check.sh
          ./scripts/pana_check.sh